import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import dayjs from 'dayjs';

/**
 * Generates PDF report for "3.7 Meta Campaign Insights – Reach Campaign"
 */
export function generateMetaReachCampaignPDF(reportData = {}, clientInfo = {}) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const clientName = clientInfo.companyName || clientInfo.name || reportData.clientName || 'Client';
  const reportDateStr = dayjs().format('MMMM D, YYYY');

  // Title Section
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(`${clientName} - Meta Ads Report`, 14, 20);

  doc.setFontSize(14);
  doc.setTextColor(236, 72, 153);
  doc.text(`3.7 Meta Campaign Insights – Reach Campaign`, 14, 30);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Purpose: Simple campaign-wise reporting for Reach campaigns. Do not add additional advertising metrics unless requested later.`, 14, 37);

  // Field Requirements Specification Table
  autoTable(doc, {
    startY: 44,
    head: [['Field', 'Requirement']],
    body: [
      ['Campaign Name', 'Name of campaign'],
      ['Type of Campaign', 'Reach'],
      ['Amount Spent', 'Campaign spend'],
      ['Views', 'Views generated by the campaign'],
      ['Reach', 'People reached by the campaign'],
      ['Followers Gained', 'Followers gained through the campaign']
    ],
    theme: 'grid',
    headStyles: {
      fillColor: [252, 231, 243], // Light pink header
      textColor: [15, 23, 42],
      fontSize: 10,
      fontStyle: 'bold',
      lineColor: [244, 114, 182],
      lineWidth: 0.3
    },
    bodyStyles: {
      textColor: [30, 41, 59],
      fontSize: 9.5,
      lineColor: [243, 244, 246],
      lineWidth: 0.2,
      cellPadding: 3.5
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 60 },
      1: { cellWidth: 122 }
    },
    margin: { left: 14, right: 14 }
  });

  // Section: Real Meta Reach Campaigns Data Table
  let nextY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 10 : 100;

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(`Connected Meta Reach Campaigns`, 14, nextY);

  const campaigns = Array.isArray(reportData.campaigns) ? reportData.campaigns : [];
  const summary = reportData.summary || {};

  const tableRows = campaigns.length > 0
    ? campaigns.map(c => [
        c.campaignName || c.campaign || 'Meta Campaign',
        c.typeOfCampaign || 'Reach',
        c.amountSpent || (typeof c.spend === 'number' ? `₹${c.spend.toLocaleString('en-IN')}` : (c.spend || '₹0')),
        (c.views ?? 0).toLocaleString('en-IN'),
        (c.reach ?? 0).toLocaleString('en-IN'),
        (c.followersGained ?? 0).toLocaleString('en-IN')
      ])
    : [
        ['No active Meta Reach campaigns connected in Performance Ads', 'Reach', '₹0', '0', '0', '0']
      ];

  // Append Total Row (Including GST)
  const totalSpentInclGst = summary.totalAmountSpentInclGst || (summary.rawTotalAmountSpentInclGst ? `₹${summary.rawTotalAmountSpentInclGst.toLocaleString('en-IN')}` : '₹0');
  const totalViewsStr = (summary.totalViews ?? 0).toLocaleString('en-IN');
  const totalReachStr = (summary.totalReach ?? 0).toLocaleString('en-IN');
  const totalFollowersStr = (summary.totalFollowersGained ?? 0).toLocaleString('en-IN');

  tableRows.push([
    'Total (Including GST)',
    'Reach',
    totalSpentInclGst,
    totalViewsStr,
    totalReachStr,
    totalFollowersStr
  ]);

  autoTable(doc, {
    startY: nextY + 6,
    head: [['Campaign Name', 'Type of Campaign', 'Amount Spent', 'Views', 'Reach', 'Followers Gained']],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [15, 23, 42], // Dark header
      textColor: [255, 255, 255],
      fontSize: 9.5,
      fontStyle: 'bold',
      lineColor: [51, 65, 85],
      lineWidth: 0.3
    },
    bodyStyles: {
      textColor: [30, 41, 59],
      fontSize: 9,
      lineColor: [203, 213, 225],
      lineWidth: 0.2,
      cellPadding: 4.5
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 55 },
      1: { cellWidth: 26, halign: 'center' },
      2: { cellWidth: 31, halign: 'right' },
      3: { cellWidth: 23, halign: 'right' },
      4: { cellWidth: 23, halign: 'right' },
      5: { cellWidth: 24, halign: 'right' }
    },
    margin: { left: 14, right: 14 },
    didParseCell: function(data) {
      if (data.section === 'body' && data.row.index === tableRows.length - 1) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = [241, 245, 249];
        data.cell.styles.textColor = [15, 23, 42];
      }
    }
  });

  // Summary Metrics Section
  nextY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 10 : 170;
  if (nextY > 230) {
    doc.addPage();
    nextY = 20;
  }

  autoTable(doc, {
    startY: nextY,
    head: [['Metric Summary', 'Value']],
    body: [
      ['Total Amount Spent (Excl. GST)', summary.totalAmountSpent || '₹0'],
      ['Total Amount Spent (Including 18% GST)', totalSpentInclGst],
      ['Total Views Generated', totalViewsStr],
      ['Total People Reached', totalReachStr],
      ['Total Followers Gained', totalFollowersStr]
    ],
    theme: 'plain',
    headStyles: {
      fillColor: [252, 231, 243],
      textColor: [15, 23, 42],
      fontSize: 9.5,
      fontStyle: 'bold'
    },
    bodyStyles: {
      textColor: [30, 41, 59],
      fontSize: 9,
      cellPadding: 3.5
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 120 },
      1: { cellWidth: 62, halign: 'right', fontStyle: 'bold' }
    },
    margin: { left: 14, right: 14 }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Performance Ads Reach Report – ${clientName} (${reportDateStr})`, 14, 287);
    doc.text(`Page ${i} of ${pageCount}`, 196, 287, { align: 'right' });
  }

  const filename = `Meta_Reach_Campaign_Report_${clientName.replace(/\s+/g, '_')}_${dayjs().format('YYYY-MM-DD')}.pdf`;
  doc.save(filename);
  return filename;
}
